### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [renatapro/zadanie12.4#1]
w pliku `Column.js` brakuje deklaracji `self` i metoda `createColumn` powinna byc zadeklarowana wewnatrz konstruktora - porownaj z `Card.js`

**Comment by renatapro** [comment]
dodatkową część zadania zrobię sobie później

**Comment by zdolny** [comment]
Nie dziala usuwanie kart:
plik `Card.js`, linia 31, jest literowka
